language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/vendor

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - sh -c "composer install --no-progress"

script: ./run-tests.sh

